# Generated by Django 3.0.8 on 2020-08-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('profile', models.TextField()),
                ('photo', models.ImageField(upload_to='photos/team')),
                ('email', models.CharField(max_length=100)),
                ('rank', models.IntegerField()),
                ('is_consultant', models.BooleanField(default=False)),
            ],
        ),
    ]
