# Generated by Django 3.0.8 on 2020-08-10 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200807_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='job_id',
        ),
    ]
