# Generated by Django 3.0.8 on 2020-08-11 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_jobapplication_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='job_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Job'),
            preserve_default=False,
        ),
    ]
