# Generated by Django 3.0.8 on 2020-12-24 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20200920_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='pdf',
            field=models.FileField(null=True, upload_to='jobs/pdf'),
        ),
    ]
