# Generated by Django 3.0.8 on 2020-12-24 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_job_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='closing',
            field=models.DateTimeField(),
        ),
    ]
