# Generated by Django 3.0.8 on 2020-08-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalblog',
            name='link',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
