# Generated by Django 3.0.8 on 2020-08-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200817_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='caption_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='caption_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='caption_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
