# Generated by Django 3.0.8 on 2020-09-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200817_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='photos/blogs'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='photos/blogs'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='photos/blogs'),
        ),
    ]
